global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'springboot-perf'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['${TARGET_SERVER_IP}:8080']
  - job_name: 'aws-ec2-os-perf'
    static_configs:
      - targets: ['${TARGET_SERVER_IP}:8080']
