export const ENV = {
    BASE_URL: __ENV.TARGET_HOST || 'http://localhost:8080',

    AUTHOR_TOKEN: __ENV.AUTHOR_TOKEN || '',
    VIEWER_TOKEN: __ENV.VIEWER_TOKEN || '',
    ADMIN_TOKEN: __ENV.ADMIN_TOKEN || '',

    TARGET_ORDER_PRODUCT_ID: 1,
    TARGET_PRODUCT_ID: 1,
    TARGET_REVIEW_ID: 8,
    TARGET_REPORT_ID: 1,
};